version: '2'
services:
  web:
    container_name: serasa-user_api-web
    networks:
      - user-api-network
    build: .
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_bd
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_DATABASE=serasa_users
      - DB_HOST_TESTE=postgres_teste_bd
      - DB_DATABASE_TESTE=serasa_users_teste
      - SEARCH_HOSTS=elasticsearch:9200
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - APP_DEBUG=true
      - KONG_PATH=${KONG_PATH}
    ports:
      - "8182:8182"
    depends_on:
      - postgres_bd
      - postgres_teste_bd
      - redis
      - elasticsearch

  redis:
    container_name: serasa-user_api-redis
    networks:
      - user-api-network
    image: "redis:4.0.11"

  postgres_bd:
    container_name: serasa-user_api-postgres
    networks:
      - user-api-network
    volumes:
      - "./sourcefiles/postgres:/var/lib/postgresql/datauser"
    image: postgres:9.5-alpine
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=serasa_users

  postgres_teste_bd:
    container_name: serasa-user_api-postgres_teste
    networks:
      - user-api-network
    image: postgres:9.5-alpine
    volumes:
      - "./sourcefiles/postgres:/var/lib/postgresql/datausertest"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=serasa_users_teste

  elasticsearch:
    container_name: serasa-user_api-elasticsearch
    networks:
      - user-api-network
    volumes:
          - "es_data:/usr/share/elasticsearch/datauser"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  es_data:

networks:
  user-api-network:
    driver: bridge
