version: '2'
services:
  web:
    container_name: serasa-order_api-web
    networks:
      - order-api-network
    build: .
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_bd
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_DATABASE=serasa_orders
      - DB_HOST_TESTE=postgres_teste_bd
      - DB_DATABASE_TESTE=serasa_orders_teste
      - SEARCH_HOSTS=elasticsearch:9200
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - APP_DEBUG=true
      - KONG_PATH=${KONG_PATH}
      - USER_API_PATH=${KONG_PATH}/user-api/
    ports:
      - "8181:8181"
    depends_on:
      - postgres_bd
      - postgres_teste_bd
      - redis
      - elasticsearch

  redis:
    container_name: serasa-order_api-redis
    image: "redis:4.0.11"
    networks:
      - order-api-network

  postgres_bd:
    container_name: serasa-order_api-postgres
    networks:
      - order-api-network
    image: postgres:9.5-alpine
    volumes:
      - "./sourcefiles/postgres:/var/lib/postgresql/dataorder"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=serasa_orders

  postgres_teste_bd:
    container_name: serasa-order_api-postgres_teste
    networks:
      - order-api-network
    image: postgres:9.5-alpine
    volumes:
      - "./sourcefiles/postgres:/var/lib/postgresql/dataordertest"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=serasa_orders_teste

  elasticsearch:
    container_name: serasa-order_api-elasticsearch
    networks:
      - order-api-network
    volumes:
      - "es_data:/usr/share/elasticsearch/dataorder"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
volumes:
  es_data:

networks:
  order-api-network:
    driver: bridge
